/**
 * Seed script to populate DynamoDB with realistic UK grocery products.
 * This bypasses the scraper and writes directly to DynamoDB via the products adapter.
 *
 * Run via: npx ts-node src/scripts/seed-products.ts
 * Or invoke as Lambda test event.
 */

import { ingestScrapedProducts } from '../adapters/products';
import { ScrapedProduct } from '../scrapers/types';
import dayjs from 'dayjs';

const now = dayjs().toISOString();

const TESCO_PRODUCTS: ScrapedProduct[] = [
  {
    storeProductId: '299463157',
    barcode: '5000128024808',
    name: 'Cravendale Semi Skimmed Milk 2L',
    brand: 'Cravendale',
    price: 195,
    pricePerUnit: 98,
    unitForPricing: 'per litre',
    clubcardPrice: 175,
    isOnOffer: true,
    offerType: 'LOYALTY_PRICE',
    offerDescription: 'Clubcard Price',
    category: 'Milk, Butter & Eggs',
    weight: '2L',
    imageUrl:
      'https://digitalcontent.api.tesco.com/v2/media/ghs/snapshotimagehandler_m/5000128024808.jpg',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/299463157',
    description: 'Cravendale Semi Skimmed Milk, filtered for purity',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '254656543',
    barcode: '5000128972345',
    name: 'Tesco British Semi Skimmed Milk 4 Pints 2.272L',
    brand: 'Tesco',
    price: 155,
    pricePerUnit: 68,
    unitForPricing: 'per litre',
    isOnOffer: false,
    category: 'Milk, Butter & Eggs',
    weight: '2.272L',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/254656543',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '290520356',
    barcode: '5000128515672',
    name: 'Warburtons Toastie Thick Sliced White Bread 800G',
    brand: 'Warburtons',
    price: 165,
    pricePerUnit: 21,
    unitForPricing: 'per 100g',
    clubcardPrice: 130,
    isOnOffer: true,
    offerType: 'LOYALTY_PRICE',
    offerDescription: 'Clubcard Price',
    category: 'Bakery',
    weight: '800g',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/290520356',
    description: 'Warburtons Toastie Thick Sliced White Bread',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '285227845',
    barcode: '5000128001234',
    name: 'Tesco Free Range Medium Eggs 10 Pack',
    brand: 'Tesco',
    price: 225,
    pricePerUnit: 23,
    unitForPricing: 'per egg',
    isOnOffer: false,
    category: 'Milk, Butter & Eggs',
    weight: '10 pack',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/285227845',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '301234567',
    barcode: '5000128045678',
    name: 'Lurpak Slightly Salted Butter 250G',
    brand: 'Lurpak',
    price: 375,
    pricePerUnit: 150,
    unitForPricing: 'per 100g',
    clubcardPrice: 325,
    isOnOffer: true,
    offerType: 'LOYALTY_PRICE',
    offerDescription: 'Clubcard Price',
    category: 'Milk, Butter & Eggs',
    weight: '250g',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/301234567',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '302345678',
    barcode: '5000128056789',
    name: 'Cathedral City Mature Cheddar 350G',
    brand: 'Cathedral City',
    price: 395,
    pricePerUnit: 113,
    unitForPricing: 'per 100g',
    clubcardPrice: 350,
    isOnOffer: true,
    offerType: 'LOYALTY_PRICE',
    offerDescription: 'Clubcard Price',
    category: 'Cheese',
    weight: '350g',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/302345678',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '303456789',
    barcode: '5000128067890',
    name: 'Tesco Boneless Chicken Breast Fillets 600G',
    brand: 'Tesco',
    price: 499,
    pricePerUnit: 832,
    unitForPricing: 'per kg',
    clubcardPrice: 425,
    isOnOffer: true,
    offerType: 'LOYALTY_PRICE',
    offerDescription: 'Clubcard Price',
    category: 'Fresh Meat & Poultry',
    weight: '600g',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/303456789',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '304567890',
    barcode: '5000128078901',
    name: 'Heinz Beanz 415G',
    brand: 'Heinz',
    price: 120,
    pricePerUnit: 29,
    unitForPricing: 'per 100g',
    isOnOffer: false,
    category: 'Tins & Cans',
    weight: '415g',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/304567890',
    description: 'Heinz Beanz in a rich tomato sauce',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '305678901',
    barcode: '5000128089012',
    name: 'Tesco Basmati Rice 1Kg',
    brand: 'Tesco',
    price: 175,
    pricePerUnit: 175,
    unitForPricing: 'per kg',
    isOnOffer: false,
    category: 'Pasta, Rice & Noodles',
    weight: '1kg',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/305678901',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '306789012',
    barcode: '5000128090123',
    name: 'Barilla Penne Pasta 500G',
    brand: 'Barilla',
    price: 175,
    pricePerUnit: 35,
    unitForPricing: 'per 100g',
    isOnOffer: false,
    category: 'Pasta, Rice & Noodles',
    weight: '500g',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/306789012',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '307890123',
    barcode: '5000128101234',
    name: 'Tesco Chopped Tomatoes 400G',
    brand: 'Tesco',
    price: 45,
    pricePerUnit: 11,
    unitForPricing: 'per 100g',
    isOnOffer: false,
    category: 'Tins & Cans',
    weight: '400g',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/307890123',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '308901234',
    barcode: '5000128112345',
    name: 'PG Tips Original Tea Bags 160 Pack',
    brand: 'PG Tips',
    price: 450,
    pricePerUnit: 3,
    unitForPricing: 'per bag',
    clubcardPrice: 375,
    isOnOffer: true,
    offerType: 'LOYALTY_PRICE',
    offerDescription: 'Clubcard Price',
    category: 'Tea',
    weight: '464g',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/308901234',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '309012345',
    barcode: '5000128123456',
    name: 'Nescafe Original Instant Coffee 200G',
    brand: 'Nescafe',
    price: 599,
    pricePerUnit: 300,
    unitForPricing: 'per 100g',
    clubcardPrice: 499,
    isOnOffer: true,
    offerType: 'LOYALTY_PRICE',
    offerDescription: 'Clubcard Price',
    category: 'Coffee',
    weight: '200g',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/309012345',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '310123456',
    barcode: '5000128134567',
    name: 'Coca-Cola Original Taste 2L',
    brand: 'Coca-Cola',
    price: 225,
    pricePerUnit: 113,
    unitForPricing: 'per litre',
    clubcardPrice: 175,
    isOnOffer: true,
    offerType: 'LOYALTY_PRICE',
    offerDescription: 'Clubcard Price',
    category: 'Soft Drinks',
    weight: '2L',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/310123456',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '311234567',
    barcode: '5000128145678',
    name: 'Tesco Bananas Loose',
    brand: 'Tesco',
    price: 25,
    pricePerUnit: 25,
    unitForPricing: 'each',
    isOnOffer: false,
    category: 'Fresh Fruit',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/311234567',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '312345678',
    barcode: '5000128156789',
    name: 'Tesco Braeburn Apples Pack Of 6',
    brand: 'Tesco',
    price: 195,
    pricePerUnit: 33,
    unitForPricing: 'each',
    isOnOffer: false,
    category: 'Fresh Fruit',
    weight: '6 pack',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/312345678',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '313456789',
    barcode: '5000128167890',
    name: 'Tesco British Whole Potatoes 2.5Kg',
    brand: 'Tesco',
    price: 175,
    pricePerUnit: 70,
    unitForPricing: 'per kg',
    isOnOffer: false,
    category: 'Fresh Vegetables',
    weight: '2.5kg',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/313456789',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '314567890',
    barcode: '5000128178901',
    name: 'Tesco Carrots 1Kg',
    brand: 'Tesco',
    price: 65,
    pricePerUnit: 65,
    unitForPricing: 'per kg',
    isOnOffer: false,
    category: 'Fresh Vegetables',
    weight: '1kg',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/314567890',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '315678901',
    barcode: '5000128189012',
    name: 'Walkers Cheese & Onion Crisps 6 Pack',
    brand: 'Walkers',
    price: 200,
    pricePerUnit: 128,
    unitForPricing: 'per 100g',
    clubcardPrice: 150,
    isOnOffer: true,
    offerType: 'LOYALTY_PRICE',
    offerDescription: 'Clubcard Price',
    category: 'Snacks & Confectionery',
    weight: '6x25g',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/315678901',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '316789012',
    barcode: '5000128190123',
    name: 'Fairy Original Washing Up Liquid 900Ml',
    brand: 'Fairy',
    price: 325,
    pricePerUnit: 36,
    unitForPricing: 'per 100ml',
    clubcardPrice: 275,
    isOnOffer: true,
    offerType: 'LOYALTY_PRICE',
    offerDescription: 'Clubcard Price',
    category: 'Household',
    weight: '900ml',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/316789012',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '317890123',
    barcode: '5000128201234',
    name: 'Andrex Classic Clean Toilet Roll 9 Pack',
    brand: 'Andrex',
    price: 595,
    pricePerUnit: 66,
    unitForPricing: 'per roll',
    clubcardPrice: 495,
    isOnOffer: true,
    offerType: 'LOYALTY_PRICE',
    offerDescription: 'Clubcard Price',
    category: 'Household',
    weight: '9 rolls',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/317890123',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '318901234',
    barcode: '5000128212345',
    name: 'Kelloggs Corn Flakes 720G',
    brand: 'Kelloggs',
    price: 375,
    pricePerUnit: 52,
    unitForPricing: 'per 100g',
    clubcardPrice: 299,
    isOnOffer: true,
    offerType: 'LOYALTY_PRICE',
    offerDescription: 'Clubcard Price',
    category: 'Cereals',
    weight: '720g',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/318901234',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '319012345',
    barcode: '5000128223456',
    name: 'Tesco Frozen Garden Peas 900G',
    brand: 'Tesco',
    price: 125,
    pricePerUnit: 14,
    unitForPricing: 'per 100g',
    isOnOffer: false,
    category: 'Frozen',
    weight: '900g',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/319012345',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '320123456',
    barcode: '5000128234567',
    name: 'Dolmio Bolognese Original Pasta Sauce 500G',
    brand: 'Dolmio',
    price: 225,
    pricePerUnit: 45,
    unitForPricing: 'per 100g',
    clubcardPrice: 175,
    isOnOffer: true,
    offerType: 'LOYALTY_PRICE',
    offerDescription: 'Clubcard Price',
    category: 'Cooking Sauces & Meal Kits',
    weight: '500g',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/320123456',
    isAvailable: true,
    scrapedAt: now,
  },
  {
    storeProductId: '321234567',
    barcode: '5000128245678',
    name: 'Hellmanns Real Mayonnaise 400G',
    brand: 'Hellmanns',
    price: 295,
    pricePerUnit: 74,
    unitForPricing: 'per 100g',
    isOnOffer: false,
    category: 'Condiments',
    weight: '400g',
    productUrl: 'https://www.tesco.com/groceries/en-GB/products/321234567',
    isAvailable: true,
    scrapedAt: now,
  },
];

async function seedProducts(): Promise<void> {
  console.log(`Seeding ${TESCO_PRODUCTS.length} Tesco products...`);

  const result = await ingestScrapedProducts(TESCO_PRODUCTS, 'TESCO');

  console.log(`Seed complete:`);
  console.log(`  Products upserted: ${result.productsUpserted}`);
  console.log(`  Prices recorded: ${result.pricesRecorded}`);
  console.log(`  Errors: ${result.errors}`);
}

// Lambda handler for invoking as a Lambda function
export const handler = async (): Promise<{
  statusCode: number;
  body: string;
}> => {
  await seedProducts();
  return {
    statusCode: 200,
    body: JSON.stringify({
      message: `Seeded ${TESCO_PRODUCTS.length} products`,
    }),
  };
};

// Direct execution
if (require.main === module) {
  seedProducts()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('Seed failed:', err);
      process.exit(1);
    });
}
