export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  VERIFY_EMAIL: '/verify-email',
  DASHBOARD: '/dashboard',
  LISTS: '/lists',
  LIST_DETAIL: '/lists/:listId',
  INVENTORY: '/inventory',
  RECIPES: '/recipes',
  RECIPE_DETAIL: '/recipes/:recipeId',
  DISCOVER_RECIPES: '/discover',
  MEAL_PLANNER: '/meal-planner',
  PRICES: '/prices',
  AI_TOOLS: '/ai-tools',
  SETTINGS: '/settings',
  PROFILE: '/profile',
} as const;
